# Generated by Django 3.0.5 on 2020-04-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stadium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='date_of_opening',
        ),
        migrations.AddField(
            model_name='stadium',
            name='year_of_opening',
            field=models.IntegerField(default=0),
        ),
    ]
