# Generated by Django 3.0.5 on 2020-04-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200414_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='year_of_opening',
            field=models.IntegerField(),
        ),
    ]
