# Generated by Django 3.0.5 on 2020-04-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='budget',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
