# Generated by Django 3.0.5 on 2020-04-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_team_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='home_stadium',
        ),
    ]
