# Generated by Django 3.0.5 on 2020-04-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200417_2223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stadium',
            unique_together={('city', 'address')},
        ),
    ]
